# DataSource Configuration
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=dbbanhang;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=false
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.use_sql_comments=false

# SQL initialization
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.continue-on-error=false

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# MVC Configuration (JSP View Resolver)
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

# Server & Main Configuration
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true
server.port=8080
